#!/bin/bash

X=`pwd`/$1
F=`pwd`/Corpus/dofast4
mkdir /tmp/xxx$$
rm -rf /tmp/dotf*line
ln -s `pwd`/Corpus/tar4 /tmp/xxx$$
ln -s `pwd`/dotf*line /tmp
cd /tmp/xxx$$
mkdir thing
cp $X thing/doc
tar zcf thing.tgz thing
$F thing
cat thing.concordance
